version: '3.6'

services:
  reverse-proxy:
    image: nginx:1.17
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on: 
      - front

  db:
    image: postgres
    environment:
      - POSTGRES_USER=rust
      - POSTGRES_DB=rust
      - POSTGRES_PASSWORD=rust
    ports:
      - 5432:5432

  front:
    build: 
      context: ./front/
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./front/.:/app
    working_dir: /app
    command: bash -c "trunk serve --address 0.0.0.0 --port=3000"
    depends_on: 
      - back  
      
  back:
    build:
      context: ./back/
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./back/.:/app
    working_dir: /app
    command: bash -c "cargo watch -x run"
    ports:
      - "3001:3001"
    depends_on: 
      - db

  postgres-keycloak:
    image: postgres:13.2
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres-keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres-keycloak
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "28080:8080"
    networks:
      - local-keycloak

networks:
  local-keycloak: